# python/lsst/sitcom/tn082/heatmap_per_HP.py

"""
Monthly stiffness heatmaps per hardpoint for M1M3 analysis.

Generates HP x Month visualizations using matplotlib, with support for
quality filters (stiff_ok, in_band), time range selection, and shared
color scaling across comparable test states.
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.figure import Figure


TESTING_STATES_DEFAULT = ("TESTINGPOSITIVE", "TESTINGNEGATIVE")

# PNG export resolution in dots per inch
DPI_PNG = 150

# Minimum figure width in inches
FIG_WIDTH_MIN = 10

# Horizontal scale factor: inches per month column
FIG_WIDTH_PER_MONTH = 0.6


# Preprocessing and helper functions

def _prep_filtered(
    df: pd.DataFrame,
    *,
    time_col: str,
    time_min_utc=None,
    time_max_utc=None,
    states=None,
    only_stiff_ok: bool = True,
    only_in_band=None,
) -> pd.DataFrame:
    """
    Apply quality filters and time range selection to the features DataFrame.

    Steps in order:
      1. Filter by test states.
      2. Filter by stiff_ok=True -> discard rows with values extremely outside the expected stiffness range.
      3. Filter by in_band -> If only_in_band is None, no filtering is applied.
      If True, keep only with values inside bands (compression/tension) rows.
      4. Convert the time column to UTC datetime and apply the [min, max] range.

    The resulting time column is stored as '_t' for internal use.

    Args:
        df: Features DataFrame generated by extract_features_for_groups.
        time_col: Name of the time column to use as the time axis.
        time_min_utc: Lower time bound (inclusive). Any format accepted
                      by pd.to_datetime.
        time_max_utc: Upper time bound (inclusive).
        states: Iterable of state names to include. None = all states.
        only_stiff_ok: If True, discard rows with stiff_ok=False or NaN.
        only_in_band: If True, keep only in_band=True rows. If False, keep
                      only in_band=False rows. If None, no band filter applied.

    Returns:
        Filtered copy of the DataFrame with '_t' column (UTC datetime).
    """
    d = df.copy()

    if states is not None:
        d = d[d["state"].isin(set(states))]

    if only_stiff_ok:
        d = d[d["stiff_ok"].fillna(False).astype(bool)]

    if only_in_band is not None:
        band = d["in_band"].fillna(False).astype(bool)
        d = d[band] if only_in_band else d[~band]

    d["_t"] = pd.to_datetime(d[time_col], utc=True, errors="coerce")

    if time_min_utc is not None:
        d = d[d["_t"] >= pd.to_datetime(time_min_utc, utc=True)]
    if time_max_utc is not None:
        d = d[d["_t"] <= pd.to_datetime(time_max_utc, utc=True)]

    return d


def clean_numeric(d: pd.DataFrame, col: str) -> pd.DataFrame:
    """
    Convert 'col' to numeric and drop rows with NaN, infinities or null '_t'.

    Args:
        d: DataFrame with '_t' column already created by _prep_filtered.
        col: Name of the numeric column to clean.

    Returns:
        Copy of the DataFrame containing only rows with finite values in
        'col' and non-null '_t'.
    """
    d = d.copy()
    d[col] = pd.to_numeric(d[col], errors="coerce")
    return d[np.isfinite(d[col]) & d["_t"].notna()]


def compute_color_limits(
    df: pd.DataFrame,
    *,
    time_col: str,
    stiffness_col: str,
    time_min_utc,
    time_max_utc,
    only_stiff_ok: bool,
    only_in_band,
) -> tuple[float, float]:
    """
    Compute global vmin and vmax over all TESTING states for shared colormap scaling.

    Used when 'states' is a subset of TESTING_STATES_DEFAULT so that separate
    subplots for TESTINGPOSITIVE and TESTINGNEGATIVE share an identical color
    scale and are visually comparable.

    Args:
        df: Original DataFrame not yet filtered by state.
        time_col: Time column name.
        stiffness_col: Stiffness column name.
        time_min_utc: Lower time bound.
        time_max_utc: Upper time bound.
        only_stiff_ok: Same value as in the main call.
        only_in_band: Same value as in the main call.

    Returns:
        Tuple (vmin, vmax) with the global stiffness range.
    """
    dscale = prep_filtered(
        df,
        time_col=time_col,
        time_min_utc=time_min_utc,
        time_max_utc=time_max_utc,
        states=TESTING_STATES_DEFAULT,
        only_stiff_ok=only_stiff_ok,
        only_in_band=only_in_band,
    )
    dscale = clean_numeric(dscale, stiffness_col)
    return (
        float(np.nanmin(dscale[stiffness_col].to_numpy())),
        float(np.nanmax(dscale[stiffness_col].to_numpy())),
    )


def build_pivot(
    d: pd.DataFrame, stiffness_col: str, agg: str
) -> pd.DataFrame:
    """
    Build the HP x Month pivot table for the heatmap.

    Rows are sorted hardpoint IDs and columns are 'YYYY-MM' strings
    sorted chronologically.

    Args:
        d: Filtered and cleaned DataFrame with '_t' column.
        stiffness_col: Stiffness column to aggregate.
        agg: Aggregation function: 'mean' or 'median'.

    Returns:
        Pivot DataFrame with HP index and month columns (Matrix).
    """
    aggfunc = "mean" if agg == "mean" else "median"
    d = d.copy()
    d["month"] = d["_t"].dt.strftime("%Y-%m")

    pivot = (
        d.pivot_table(
            index="hp",
            columns="month",
            values=stiffness_col,
            aggfunc=aggfunc,
        )
        .sort_index()
    )
    return pivot.reindex(sorted(pivot.columns), axis=1)


# Main function

def plot_monthly_heatmap_stiffness(
    df: pd.DataFrame,
    *,
    time_col: str = "t_start_utc",
    stiffness_col: str = "stiffness_N_per_um",
    agg: str = "mean",
    states=None,
    only_stiff_ok: bool = True,
    only_in_band=None,
    time_min_utc=None,
    time_max_utc=None,
    cmap: str = "viridis",
    title: str | None = None,
    show: bool = True,
    save_png: bool = False,
    output_dir: str = "outputs",
) -> str | Figure | None:
    """
    Generate a monthly stiffness heatmap with Hardpoint x Month axes.

    Each cell color represents the aggregated stiffness
    of all tests for that HP in that month, after applying quality filters.

    Outlier filters:
      - 'only_stiff_ok=True': excludes stiffness values outside the expected
        range.
      - 'only_in_band=True': keeps only tests whose breakaway force falls
        within the accepted compression or tension bands.
      - 'only_in_band=False': keeps only out-of-band tests (outliers).
      - 'only_in_band=None': no band filter applied (default).

    Shared color scaling:
      If 'states' is a subset of TESTING_STATES_DEFAULT, vmin and vmax are
      computed over the global range of both testing states. This allows
      subplots for TESTINGPOSITIVE and TESTINGNEGATIVE to share the same
      color scale for direct visual comparison.

    Args:
        df: Features DataFrame.
        time_col: Time column used as reference (default: 't_start_utc').
        stiffness_col: Stiffness column to visualize (default: 'stiffness_N_per_um').
        agg: Aggregation function per cell: 'mean' or 'median'.
        states: List of states to include. None = all states present.
        only_stiff_ok: If True, filter by stiff_ok=True (default: True).
        only_in_band: Band filter: True, False or None (no filter).
        time_min_utc: Lower time bound of the range to plot.
        time_max_utc: Upper time bound of the range to plot.
        cmap: Matplotlib colormap name (default: 'viridis').
        title: Plot title. If None, generated automatically.
        show: If True, call plt.show().
        save_png: If True, save the plot as PNG to 'output_dir'
                  and return the file path.
        output_dir: Output directory when save_png=True.

    Returns:
        - str with the PNG file path if save_png=True.
        - None if show=True.
        - Matplotlib Figure if show=False and save_png=False.

    Raises:
        ValueError: If no data remains after applying the filters.
        ValueError: If 'agg' is not 'mean' or 'median'.
)
    """
    if agg not in ("mean", "median"):
        raise ValueError(f"agg must be 'mean' or 'median', got: '{agg}'")

    # Filter and clean
    d = prep_filtered(
        df,
        time_col=time_col,
        time_min_utc=time_min_utc,
        time_max_utc=time_max_utc,
        states=states,
        only_stiff_ok=only_stiff_ok,
        only_in_band=only_in_band,
    )
    d = clean_numeric(d, stiffness_col)

    if d.empty:
        raise ValueError(
            "No data available for plotting after applying filters. "
            "Check the state, time range, and quality filter parameters."
        )

    # Build pivot table 
    pivot = build_pivot(d, stiffness_col, agg)
    mat = pivot.to_numpy()

    # Colormap limits for shared scaling across testing states.
    s = set(states) if states is not None else set()
    if states is not None and s.issubset(set(TESTING_STATES_DEFAULT)):
        vmin, vmax = compute_color_limits(
            df,
            time_col=time_col,
            stiffness_col=stiffness_col,
            time_min_utc=time_min_utc,
            time_max_utc=time_max_utc,
            only_stiff_ok=only_stiff_ok,
            only_in_band=only_in_band,
        )
    else:
        # Local scale: use the range of the current data only
        vmin = float(np.nanmin(mat))
        vmax = float(np.nanmax(mat))

    # Plot
    fig_width = max(FIG_WIDTH_MIN, FIG_WIDTH_PER_MONTH * pivot.shape[1])
    fig, ax = plt.subplots(figsize=(fig_width, 4.5), constrained_layout=True)

    im = ax.imshow(
        mat,
        aspect="auto",
        interpolation="nearest",
        vmin=vmin,
        vmax=vmax,
        cmap=cmap,
    )

    # Axis ticks and labels
    ax.set_yticks(np.arange(pivot.shape[0]))
    ax.set_yticklabels([f"HP{int(h)}" for h in pivot.index])
    ax.set_xticks(np.arange(pivot.shape[1]))
    ax.set_xticklabels(pivot.columns, rotation=45, ha="right")
    ax.set_xlabel("Month (UTC)")
    ax.set_ylabel("Hardpoint")

    # Colorbar
    cbar = fig.colorbar(im, ax=ax)
    cbar.set_label(f"Stiffness {agg} (N/µm)")

    # Auto-generate title
    if title is None:
        st_label = ",".join(states) if states is not None else "ALL"
        title = f"Monthly heatmap: {agg} stiffness | states={st_label}"
    ax.set_title(title)

    # Output
    if save_png:
        os.makedirs(output_dir, exist_ok=True)
        state_part = "ALL" if states is None else "-".join(states)
        filename = f"heatmap_stiffness_{agg}_{state_part}.png"
        path = os.path.join(output_dir, filename)
        fig.savefig(path, dpi=DPI_PNG, bbox_inches="tight")
        plt.close(fig)
        return path

    if show:
        plt.show()
        return None

    return fig
